{% set version = "1.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bmlephoto
  version: {{ version|replace("-", "_") }}

source:
  path: ../../models/BML-ePhotosynthesis/

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=3.6.0
    - ephotosynthesis
  run:
    - r-base >=3.6.0
    - ephotosynthesis
    - r-biocro >=3.1.0

test:
  commands:
    - $R -e "library('BMLePhoto')"           # [not win]
    - "\"%R%\" -e \"library('BMLePhoto')\""  # [win]

about:
  home: https://github.com/Matthews-Research-Group/BML-ePhotosynthesis
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: ePhotosynthesis BioCro module
  description: |
    bmlephoto includes a BioCro module that calls the ePhotosynthesis C++ library.
  doc_url: https://github.com/Matthews-Research-Group/BML-ePhotosynthesis
  dev_url: https://github.com/Matthews-Research-Group/BML-ePhotosynthesis

extra:
  recipe-maintainers:
    - langmm
