{% set version = "1.0.0" %}

package:
  name: r-yggdrasilbml
  version: {{ version|replace("-", "_") }}

source:
  path: ../../

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - ephotosynthesis
    - yggdrasil
  run:
    - r-base
    - ephotosynthesis
    - r-biocro >=3.1.0
    - yggdrasil

test:
  commands:
    - $R -e "library('BioCro')"           # [not win]
    - "\"%R%\" -e \"library('BioCro')\""  # [win]

about:
  home: https://github.com/cropsinsilico/BML-yggdrasil
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: yggdrasil enabled BioCro modules
  description: |
    yggdrasilBML contains a set of BioCro modules that call external models using yggdrasil.
  doc_url: https://github.com/cropsinsilico/BML-yggdrasil
  dev_url: https://github.com/cropsinsilico/BML-yggdrasil

extra:
  recipe-maintainers:
    - langmm
